#!/bin/bash

docker-compose build
docker-compose run --rm app gem install bundler
docker-compose run --rm app bundle
docker-compose run --rm app ruby get_dataset.rb
docker-compose up -d es
echo "Booting elasticsearch...wating 10s"
sleep 10s
echo "Elasticsearch booted, putting data"
curl -XPUT $(docker-machine ip default):9200/_bulk --data-binary "@lottery.json"
echo "You're done. Great Job!"

